site_name: test-docs
site_description: Documentation for My Project
site_author: Your Name
# site_url: https://example.com

docs_dir: docs

theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Guides:
      - Getting Started: guides/getting-started.md
      - Advanced Usage: guides/advanced.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  # Uncomment if using versioning or other plugins
  # - git-revision-date
  # - mkdocstrings

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
